### ISSUE TITLE
Getting SPAM and non-sense pull requests?

### ISSUE THREAD

**Issue by alvarotrigo** [davearonson/pull-request-roulette#41]
I've noticed some of the traffic my repository has comes from http://www.pullrequestroulette.com/ and I noticed it about the same time that mysterious and non-sense pull requests started to appear in my repository.

See the following ones:
https://github.com/alvarotrigo/fullPage.js/pull/3765
https://github.com/alvarotrigo/fullPage.js/pull/3764
https://github.com/alvarotrigo/fullPage.js/pull/3761
https://github.com/alvarotrigo/fullPage.js/pull/3750
https://github.com/alvarotrigo/fullPage.js/pull/3749
https://github.com/alvarotrigo/fullPage.js/pull/3747
https://github.com/alvarotrigo/fullPage.js/pull/3745

What's going on here?

**Comment by davearonson** [comment]
@alvarotrigo , most of those seem to be from people who want to just game the system and make whatever tiny insignificant PRs they can, just to claim they have "done Hacktoberfest", or maybe even cheating on the even broader and simpler claim of having "contributed to Open Source".  These jackasses will use whatever source they can, to find projects they can "contribute" to.  PRR is just one more way they can find out about some existing projects on Github, beyond the bazillions of other listings of projects, Googling for them, browsing Github directly, etc. etc. etc.

I'll try to find some time today to go into my database and remove your project's closed PR.  That should stem the flow of any such miscreants being directed to you from PRR.

**Comment by alvarotrigo** [comment]
Thanks for that! ;)

**Comment by davearonson** [comment]
I've removed yours, and the others that were not still open, so I'm going to close this.  A PR for a feature that would check once in a while, or when someone tries to "take" a PR, or at some point, would be very welcome.  :-)
