### ISSUE TITLE
Broken link on webpage

### ISSUE THREAD

**Issue by schneiderl** [davearonson/pull-request-roulette#42]
Hi, 
On your the [homepage](http://www.pullrequestroulette.com/) there is a link to a [animation library](http://www.animationlibrary.com/animation/27468/Roulette_spins/) which is broken.

Thank you for your project and time.

**Comment by davearonson** [comment]
It might have been broken for you at the time, but it's working for me now.  Well, kinda sorta.  The _link_ works, but their _site_ is broken, having some kind of internal error.  For now, I'll trust that they'll fix it eventually.  (And that even if the specific path is no longer valid, they'll do something reasonable with it.)

**Comment by schneiderl** [comment]
@davearonson Oh you're right. I thought it was a 404 for some reason. My bad.
